### ISSUE TITLE
History Logging

### ISSUE THREAD

**Issue by thlinux** [PPA-Enterprises/crispy-fiesta#14]
Client wants history logging feature on users on a per job basis. Meaning, any creations, edits, and deletions are logged per job, and per client. This will include what they changed, and when they changed. I am also thinking about adding a "roleback" feature on each entry of the log. That way if someone messes up, admin can roleback to any previous change.

**Comment by joshbenz** [comment]
How complex do we want to make the rollback feature @thlinux? One idea to keep the history is to do it similar to how Git does it. That is, Only keep track of the changes themselves. In that case, do we want rollbacks to enforce a linear type of ordering. For example, I have changes tagged as 1 2 3 4 5. 5 has the latest changes. Lets say that the changes in 2 are incorrect. So I need to undo those changes. In the case that 2 affects 3 and 3 affects 4 and 4 affects 5, in order to be consistent, I need to rollback 5, 4, 3, and 2. The downside is that any other changes that were contained in those tags are lost as well.
- Option 1: to fix this is to rollback and then try to recompute the changes back up to 5. I worry about cascading effect(eg. rolling back changes on client might also affect a job or multiple jobs) and complexity of this. We would need to isolate the affected records (depending on the granularity that we want) and block/put on hold any edits from all frontend clients until the rollback (including the re-computation) is finished. And then we can service all the other requests that were on hold. We also have to decide, can we rollback a rollback?
-  Option 2: is to just let them be lost.

Option 3: Don't do rollbacks, make the Event Log similar to how Event Sourcing works. I like the rollback idea and I think it would be fun to implement, but I also question the need to add such a feature. If something is wrong, they can simply edit the record itself and that edit will be appended to the log. So they start in tag 5 and just edit whatever is wrong and append the edit as tag 6. That is certainly better for them than option 2 and they still maintain the integrity of the event log. I just can't think of a case where a rollback is used that can't be done with an edit, especially since their data isn't very complex.
